<?php
// This file generated by Propel 1.7.0-dev convert-conf target
// from XML runtime conf file /home/chris/workspace/Signage/application/database/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'signage' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        //'classname' => 'DebugPDO',
        'dsn' => 'mysql:host=localhost;dbname=signage',
        'user' => 'signage',
        'password' => 'jsmqFr5qP4DtF9a7',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'signage',
  ),
/*  'log' => 
  array (
    'type' => 'file',
    'name' => '/home/chris/workspace/Signage/propel.log',
    'ident' => 'propel',
    'level' => '7',
  ),*/
  'generator_version' => '1.7.0-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'propel-classmap.php');
return $conf;